### PR TITLE
Vestibulum is now Sphido CMS

### PR DESCRIPTION
**Pull request by OzzyCzech**
Vestibulum became Sphido cms with own logo and website

### CODE REVIEW

**Comment by OzzyCzech** [comment]
@ahadb any news? :) about my PR

**Comment by OzzyCzech** [comment]
@ahadb hi again, how it's look? can you merge it?

**Comment by OzzyCzech** [comment]
@ahadb any news about my PR?

**Comment by OzzyCzech** [comment]
@ahadb any news...?

**Comment by OzzyCzech** [comment]
PR was updated @ahadb can you please merge it?

**Comment by ahadb** [comment]
Hi @OzzyCzech - if you reopen your PR I will merge it in. Thanks.

**Comment by OzzyCzech** [comment]
Thanks here it is ... #51

**Pull request closed without merging**
